services:
  api:
    build: ./app
    # Bind this service to the model and inject URL/ID as env vars
    models:
      llm:
        endpoint_var: LLM_URL
        model_var: LLM_ID
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"

models:
  llm:
    model: hf.co/Triangle104/SmolLM3-3B-Q4_K_M-GGUF:Q4_K_M