services:
  api:
    build: ./app
    models:
      dmr_embedder_model:
        endpoint_var: EMBEDDER_URL
        model_var: EMBEDDER_ID
    environment:
      PORT: "8080"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ~/.aws:/root/.aws:ro
    ports:
      - "8080:8080"

models:
  dmr_embedder_model:
    model: hf.co/nomic-ai/nomic-embed-text-v1.5-GGUF:Q4_K_M