networks:
  internal_net:
    internal: true
  public_net: {}

volumes:
  llama-cache:
  ollama:

services:
  api:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./resources:/app_v1/resources
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - public_net

  ollama:
    image: ollama/ollama:latest # Can change image for GPU support
    command: ["serve"]
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - public_net