networks:
  internal_net:
    internal: true
  public_net: {}

volumes:
  llama-cache:
  ollama:

services:
  api:
    build: ./backend
    environment:
      GEMINI_API_URL: ${GEMINI_API_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      JWT_SECRET: ${JWT_SECRET}
      EMBEDDER_URL: "http://ollama:11434"
      EMBEDDER_ID: "nomic-embed-text:latest"
    volumes:
      - ./resources:/app_v1/resources
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - public_net

  ollama:
    image: ollama/ollama:latest
    command: ["serve"]
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - public_net